### ISSUE TITLE
请求添加友链

### ISSUE THREAD

**Issue by Avimitin** [moodyhunter/moodyhunter#4]
my name is/我是: sh1marin
and my website is at的网站在 https://sh1mar.in

- [x] I want to add my site to your friends' links/我想将自己的网站添加到友链

A short description in one sentence/一句话介绍一下？

> 我单推 moody，贴贴 moody！

**Comment by moodyhunter** [comment]
！好快

**Comment by Avimitin** [comment]
我有空也给自己加个友链的单页
