### ISSUE TITLE
请求添加友链

### ISSUE THREAD

**Issue by axionl** [moodyhunter/moodyhunter#5]
# Nice to meet you!

- My name is / 我的名字是
  - `axionl`
- My website is at / 我的网站域名为:
  - `axionl.me`
- URL to my Avatar (leave blank for GitHub Avatar) / 头像的 URL（留空则使用 GitHub 头像）
  - 

- [x] I want to add my site to your friends' links/我想将自己的网站添加到友链

A short description in one sentence/一句话介绍一下？

> 「 一個你知道的地方，和一個沒有酒的故事 ｜ 言文 」

**Comment by moodyhunter** [comment]
~~浇浇，css 里怎么根据文字长度自适应 font size~~
