### ISSUE TITLE
请求添加友链

### ISSUE THREAD

**Issue by CoelacanthusHex** [moodyhunter/moodyhunter#6]
# Nice to meet you!

- My name is / 我的名字是
  - `Coelacanthus`
- My website is at / 我的网站域名为:
  - `blog.coelacanthus.moe`
- URL to my Avatar (leave blank for GitHub Avatar) / 头像的 URL（留空则使用 GitHub 头像）
  - `https://blog.coelacanthus.moe/icon.png`

- [x] I want to add my site to your friends' links/我想将自己的网站添加到友链

A short description in one sentence/一句话介绍一下？

> Moody 的朋友里最菜的一个

**Comment by moodyhunter** [comment]
这也太假了（x
