### ISSUE TITLE
I wanna eat moody

### ISSUE THREAD

**Issue by AkinoKaede** [moodyhunter/moodyhunter#8]
# Nice to meet you!

- My name is / 我的名字是
  - `秋のかえで`
- My website is at / 我的网站域名为:
  - `blog.akinokae.de`
- URL to my Avatar (leave blank for GitHub Avatar) / 头像的 URL（留空则使用 GitHub 头像）

- [x] I want to add my site to your friends' links/我想将自己的网站添加到友链

A short description in one sentence/一句话介绍一下？
I wanna eat moody
>

**Comment by moodyhunter** [comment]
done, see https://github.com/moodyhunter/moodyhunter.github.io/commit/45e71d846193ae95f076263bd2defed4c3d49afb
