### ISSUE TITLE
我要加友链！

### ISSUE THREAD

**Issue by hiifong** [moodyhunter/moodyhunter#9]
# Nice to meet you!

- My name is / 我的名字是
  - `hiifong`
- My website is at / 我的网站域名为:
  - `hiif.ong`
- URL to my Avatar (leave blank for GitHub Avatar) / 头像的 URL（留空则使用 GitHub 头像）
  - `https://hiif.ong/logo.png`

- [x] I want to add my site to your friends' links/我想将自己的网站添加到友链

A short description in one sentence/一句话介绍一下？

> Hi 👋, I'm hiifong!

**Comment by hiifong** [comment]
大佬你好呀,我想跟你互加友链,不知道可不可以?

**Comment by moodyhunter** [comment]
好哦 :)

**Comment by moodyhunter** [comment]
done @ https://github.com/moodyhunter/moodyhunter.github.io/commit/a51e83372fae68f1cde689c83f54371099f886a7
